config/routes.rb
Rails.application.routes.draw do
  resources :books
  get '/top' => 'homes#top'
  root to: 'homes#top'
  # get 'lists/index'
  # post 'lists' => 'lists#create'
  # get 'lists/:id' => 'lists#show',as: 'book'
  # get 'lists/:id/edit' => 'lists#edit', as: 'edit_book'
  # patch 'lists/:id' => 'lists#update', as: 'update_book'
  # delete 'lists/:id' => 'lists#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end

    flash[:notice] = "Book was successfully created."
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.new(book_params)
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      render :show
    else
      @books = Book.all
      render :index
    end
    
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
    flash[:notice] = "Book was successfully destroyed."
  end

private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to list_path(@book.id)
    else
      @books = Book.all
      render :index
    end

    flash[:notice] = "Book was successfully created."
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.new(book_params)
    if @book.update(book_params)
      redirect_to list_path(@book.id)
    else
      @books = Book.all
      render :index
    end

    flash[:notice] = "Book was successfully updated."
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/lists'
    flash[:notice] = "Book was successfully destroyed."
  end

private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def page_title
    title = "Booker"
    title = @page_title + " | " + title if @page_title
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book,url: book_path(@book.id),method: :patch do |f| %>

<div class="new">
  <p class="new-text">Title</p>
   <%= f.text_field :title %>
</div>

<div class="new">
  <p class="new-text">Body</p>
   <%= f.text_area :body %>
</div>
 
 <div class="update"><%= f.submit 'Update Book' %></div>
<br>
 <%= link_to "Show", book_path(@book.id) %>
 |
 <%= link_to "Back",books_path ,method: :get %>

 <% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>

<% end %>

<h1>Books</h1>
<!-- 一覧表 -->
<table width="40%">
  <tr>
    <th width="20%">Title</th>
    <th width="40%">Body</th>
    <th width="20%">    </th>
  </tr>

  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>

    <td>
      <%= link_to "Show", book_path(book.id) %>
      <%= link_to "Edit",edit_book_path(book.id),method: :get %>
      <%= link_to "Destroy",book_path(book.id),method: :delete, data: { confirm: "Are you sure？" } %>
    </td>
  </tr>
    <% end %>
  
  </table>

<!-- 投稿box -->
  <h2>New book</h2>
  <%= form_with model: @books,url: '/books',method: :post do |f| %>


  <% if @book.errors.any? %>
  <div class="error-box">
    <h4><%= @book.errors.count %> errors prohibited this book from being saved:</h4>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
   </div>
  
  <div class="new">
    <p class="new-text">Title</p>
    <%= f.text_field :title %>
  </div>
  <div class="new">
    <p class="new-text">Body</p>
    <%= f.text_area :body %>
  </div>

  <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>

<% end %>

<p><strong>Title:</strong> <%= @book.title %></p>

<p><strong>Body:</strong> <%= @book.body %></p>

<%= link_to "Edit",edit_book_path(@book.id) %>
|
<%= link_to "Back",books_path ,method: :get %>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
  </h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<%= link_to "start", '/books' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book,url: list_path(@book.id),method: :patch do |f| %>

<div class="new">
  <p class="new-text">Title</p>
   <%= f.text_field :title %>
</div>

<div class="new">
  <p class="new-text">Body</p>
   <%= f.text_area :body %>
</div>
 
 <div class="update"><%= f.submit 'Update Book' %></div>
<br>
 <%= link_to "Show", list_path(@book.id) %>
 |
 <%= link_to "Back",lists_path ,method: :get %>

 <% end %>

app/views/lists/index.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>

<% end %>

<h1>Books</h1>
<!-- 一覧表 -->
<table width="40%">
  <tr>
    <th width="20%">Title</th>
    <th width="40%">Body</th>
    <th width="20%">    </th>
  </tr>

  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>

    <td>
      <%= link_to "Show", list_path(book.id) %>
      <%= link_to "Edit",edit_list_path(book.id),method: :get %>
      <%= link_to "Destroy",list_path(book.id),method: :delete, data: { confirm: "Are you sure？" } %>
    </td>
  </tr>
    <% end %>
  
  </table>

<!-- 投稿box -->
  <h2>New book</h2>
  <%= form_with model: @books,url: '/lists',method: :post do |f| %>


  <% if @book.errors.any? %>
  <div class="error-box">
    <h4><%= @book.errors.count %> errors prohibited this book from being saved:</h4>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
   </div>
  
  <div class="new">
    <p class="new-text">Title</p>
    <%= f.text_field :title %>
  </div>
  <div class="new">
    <p class="new-text">Body</p>
    <%= f.text_area :body %>
  </div>

  <%= f.submit 'Create Book' %>
  <% end %>

app/views/lists/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>

<% end %>

<p><strong>Title:</strong> <%= @book.title %></p>

<p><strong>Body:</strong> <%= @book.body %></p>

<%= link_to "Edit",edit_list_path(@book.id) %>
|
<%= link_to "Back",lists_path ,method: :get %>